name: Docker Image j

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:

build:

runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- name: Build the Docker image
run: docker push cr.yandex/crpo30oaoogvq1b1e6l6/dz1:latest
