name: Docker Image a

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:

build:

runs-on: dz1-latest

steps:
- uses: actions/checkout@v1
- name: Build the Docker image
run: docker push cr.yandex/crpo30oaoogvq1b1e6l6/dz1:latest
